# Generated by Django 6.0.2 on 2026-02-12 23:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitiveStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_games", models.IntegerField(default=0)),
                ("games_won", models.IntegerField(default=0)),
                ("games_lost", models.IntegerField(default=0)),
                ("total_sets_won", models.IntegerField(default=0)),
                ("total_sets_lost", models.IntegerField(default=0)),
                ("total_points_scored", models.IntegerField(default=0)),
                ("highest_score_in_game", models.IntegerField(default=0)),
                ("six_bonuses_earned", models.IntegerField(default=0)),
                ("seven_bonuses_earned", models.IntegerField(default=0)),
                ("steal_bonuses_earned", models.IntegerField(default=0)),
                ("total_fouls", models.IntegerField(default=0)),
                ("current_win_streak", models.IntegerField(default=0)),
                ("best_win_streak", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitive_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Competitive stats",
                "db_table": "competitive_stats",
            },
        ),
        migrations.CreateModel(
            name="PracticeStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_games", models.IntegerField(default=0)),
                ("games_won", models.IntegerField(default=0)),
                ("wins_vs_beginner", models.IntegerField(default=0)),
                ("wins_vs_intermediate", models.IntegerField(default=0)),
                ("wins_vs_advanced", models.IntegerField(default=0)),
                ("wins_vs_expert", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Practice stats",
                "db_table": "practice_stats",
            },
        ),
    ]
