# Generated by Django 6.0.2 on 2026-02-12 23:32

import apps.lobby.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("quick_match", "Quick Match (1v1)"),
                            ("multiplayer", "Multiplayer Lobby"),
                            ("private", "Private Room"),
                            ("practice", "Practice Mode"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        default=apps.lobby.models.generate_room_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
                ("target_score", models.IntegerField(default=12)),
                ("max_players", models.IntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Players"),
                            ("starting", "Starting Soon"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("countdown_started_at", models.DateTimeField(blank=True, null=True)),
                ("countdown_duration", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room",
                        to="game.game",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "game_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchmakingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("quick_match", "Quick Match"),
                            ("multiplayer", "Multiplayer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_score", models.IntegerField(default=12)),
                ("is_matched", models.BooleanField(default=False)),
                ("joined_queue_at", models.DateTimeField(auto_now_add=True)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "matched_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_from_queue",
                        to="lobby.gameroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchmaking_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "matchmaking_queue",
                "ordering": ["joined_queue_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "bot_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("left", "Left"),
                            ("kicked", "Kicked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_ready", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_players",
                        to="lobby.gameroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "room_players",
                "ordering": ["joined_at"],
                "unique_together": {("room", "user")},
            },
        ),
    ]
