# Generated by Django 6.0.2 on 2026-03-27 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roomplayer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="roomplayer",
            name="guest_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="roomplayer",
            name="is_host",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gameroom",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosted_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
