# Generated by Django 6.0.2 on 2026-02-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="guest_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
